
/*
	GENERATED BY:
  	generate-app-entry.js
	DO NOT EDIT MANUALLY
*/

/* Import every component in src/components */
import AlertBox from './components/AlertBox/AlertBox.vue';
import AlertPopUp from './components/AlertPopUp/AlertPopUp.vue';
import Checkbox from './components/Checkbox/Checkbox.vue';
import Input from './components/Input/Input.vue';
import NavBar from './components/NavBar/NavBar.vue';
import PopUp from './components/PopUp/PopUp.vue';
import QuickPeek from './components/QuickPeek/QuickPeek.vue';
import SearchForm from './components/SearchForm/SearchForm.vue';
import Select from './components/Select/Select.vue';
import SideBar from './components/SideBar/SideBar.vue';
import Table from './components/Table/Table.vue';

/* Export components individually */
export { AlertBox, AlertPopUp, Checkbox, Input, NavBar, PopUp, QuickPeek, SearchForm, Select, SideBar, Table };

/* Use every component when the library is installed as a Vue plugin */
function install(Vue) {
	Vue.component('vuetiful-alert-box', AlertBox);
	Vue.component('vuetiful-alert-pop-up', AlertPopUp);
	Vue.component('vuetiful-checkbox', Checkbox);
	Vue.component('vuetiful-input', Input);
	Vue.component('vuetiful-nav-bar', NavBar);
	Vue.component('vuetiful-pop-up', PopUp);
	Vue.component('vuetiful-quick-peek', QuickPeek);
	Vue.component('vuetiful-search-form', SearchForm);
	Vue.component('vuetiful-select', Select);
	Vue.component('vuetiful-side-bar', SideBar);
	Vue.component('vuetiful-table', Table);
}

/* Export the library as a plugin */
export default { install: install };
